{{- if gt (int .Values.autoscaling.minReplicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aura-service.name" . }}
  labels:
    {{- include "aura-service.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "aura-service.selectorLabels" . | nindent 6 }}
{{- end }}
